spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${db_url}
    username: ${db_usuario}
    password: ${db_senha}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true